package net.itskittyyoutube.kitty;

import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.registry.FlammableBlockRegistry;
import net.fabricmc.fabric.api.registry.StrippableBlockRegistry;
import net.itskittyyoutube.kitty.block.TheBedrockSMPBlocks;
import net.itskittyyoutube.kitty.item.TheBedrockSMPItems;
import net.itskittyyoutube.kitty.sound.TheBedrockSMPSounds;
import net.itskittyyoutube.kitty.tab.TheBedrockSMPCreativeTabs;
import net.itskittyyoutube.kitty.world.gen.TheBedrockSMPWorldGeneration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class TheBedrockSMP implements ModInitializer {
	public static final String MOD_ID = "kitty";
	public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);

	@Override
	public void onInitialize() {
        TheBedrockSMPItems.registerItems();
        TheBedrockSMPSounds.registerSounds();
        TheBedrockSMPCreativeTabs.registerTabs();
        TheBedrockSMPBlocks.registerBlocks();
        TheBedrockSMPWorldGeneration.WorldGen();

        StrippableBlockRegistry.register(TheBedrockSMPBlocks.CHERRY_BIRCH_LOG, TheBedrockSMPBlocks.STRIPPED_CHERRY_BIRCH_LOG);
        StrippableBlockRegistry.register(TheBedrockSMPBlocks.CHERRY_BIRCH_WOOD, TheBedrockSMPBlocks.STRIPPED_CHERRY_BIRCH_WOOD);

        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CHERRY_BIRCH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CHERRY_BIRCH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.STRIPPED_CHERRY_BIRCH_LOG, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.STRIPPED_CHERRY_BIRCH_WOOD, 5, 5);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CHERRY_BIRCH_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CHERRY_BIRCH_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CHERRY_BIRCH_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CHERRY_BIRCH_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CHERRY_BIRCH_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PLANKS_TEMPLATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.WHITE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_GRAY_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GRAY_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLACK_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BROWN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.RED_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.ORANGE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.YELLOW_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIME_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GREEN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CYAN_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_BLUE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLUE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PURPLE_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.MAGENTA_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PINK_PLANKS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.WHITE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_GRAY_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GRAY_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLACK_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BROWN_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.RED_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.ORANGE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.YELLOW_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIME_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GREEN_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CYAN_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_BLUE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLUE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PURPLE_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.MAGENTA_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PINK_SLAB, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.WHITE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_GRAY_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GRAY_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLACK_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BROWN_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.RED_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.ORANGE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.YELLOW_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIME_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GREEN_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CYAN_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_BLUE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLUE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PURPLE_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.MAGENTA_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PINK_FENCE_GATE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.WHITE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_GRAY_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GRAY_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLACK_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BROWN_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.RED_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.ORANGE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.YELLOW_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIME_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GREEN_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CYAN_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_BLUE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLUE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PURPLE_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.MAGENTA_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PINK_FENCE, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.WHITE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_GRAY_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GRAY_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLACK_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BROWN_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.RED_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.ORANGE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.YELLOW_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIME_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.GREEN_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CYAN_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.LIGHT_BLUE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.BLUE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PURPLE_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.MAGENTA_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.PINK_STAIRS, 5, 20);
        FlammableBlockRegistry.getDefaultInstance().add(TheBedrockSMPBlocks.CHERRY_BIRCH_LEAVES, 30, 60);
    }
}
